# Runs Bazel tests for DeepMind Lab

os: osx

sudo: true

language: c++

osx_image: xcode9.3

jdk:
  - oraclejdk8

addons:
  homebrew:
    taps:
      - bazelbuild/tap

before_install:
  - brew install bazel glib sdl2 python python@2
  - sudo pip install numpy
  - sudo pip3 install numpy

script:
  - find -L /usr/local/Cellar -type f -name Python.h -o -name arrayobject.h -o -name SDL.h -o -name glib.h
  - bazel build -c opt --copt=-Wno-sign-compare --show_progress_rate_limit=10 //:game
