# Runs Bazel tests for DeepMind Lab

language: c++

dist: xenial

jdk:
  - oraclejdk8

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'
    packages:
      - bazel
      - libffi-dev
      - gettext
      - freeglut3-dev
      - libsdl2-dev
      - libosmesa6-dev
      - python-dev
      - python-numpy
      - python-pil
      - python3-dev
      - python3-numpy
      - python3-pil

script:
  - case "${CXX}" in
      "g++")
        bazel test --show_progress_rate_limit=20 --test_output=errors -c opt --dynamic_mode=off --copt=-Wno-sign-compare --copt=-Wno-maybe-uninitialized //... ;
        bazel run -c opt --dynamic_mode=off --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare //:python_random_agent --define headless=osmesa ;
        ;;
      "clang++")
        bazel test --show_progress_rate_limit=20 --test_output=errors -c opt --dynamic_mode=off --copt=-Wno-sign-compare --copt=-Wno-uninitialized --cxxopt=-std=c++11 //... ;
        bazel run -c opt --dynamic_mode=off --copt=-Wno-maybe-uninitialized --copt=-Wno-sign-compare --cxxopt=-std=c++11 //:python_random_agent --define headless=osmesa ;
        ;;
    esac
